[2022-05-24 12:05:40,470] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-05-24T12:05:37.701626+00:00 [queued]>
[2022-05-24 12:05:40,481] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-05-24T12:05:37.701626+00:00 [queued]>
[2022-05-24 12:05:40,481] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-24 12:05:40,481] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-24 12:05:40,481] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-24 12:05:40,494] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-05-24 12:05:37.701626+00:00
[2022-05-24 12:05:40,498] {standard_task_runner.py:52} INFO - Started process 998 to run task
[2022-05-24 12:05:40,502] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2022-05-24T12:05:37.701626+00:00', '--job-id', '36', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpvxmppp08', '--error-file', '/tmp/tmpeqim8kwl']
[2022-05-24 12:05:40,503] {standard_task_runner.py:80} INFO - Job 36: Subtask run_after_loop
[2022-05-24 12:05:40,556] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2022-05-24T12:05:37.701626+00:00 [running]> on host 7fff3450d977
[2022-05-24 12:05:40,780] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-05-24T12:05:37.701626+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-24T12:05:37.701626+00:00
[2022-05-24 12:05:40,781] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-24 12:05:40,781] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-05-24 12:05:40,792] {subprocess.py:85} INFO - Output:
[2022-05-24 12:05:40,795] {subprocess.py:92} INFO - 1
[2022-05-24 12:05:40,796] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-24 12:05:40,824] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220524T120537, start_date=20220524T120540, end_date=20220524T120540
[2022-05-24 12:05:40,873] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-24 12:05:40,906] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
